class_name PackageRepository
extends RefCounted

const PackageDocumentCacheScript := preload("res://src/infrastructure/packages/package_document_cache.gd")
const EXPECTED_SCHEMA_HASH: String = "12376856235a11f507b993835acad87b546f87b9ad519533967ed2701ddb89cd"
const DECODER_VERSION: int = 5
const REQUIRED_DOCUMENTS: Array[String] = ["assets/index.json", "content.json", "scenario.json", "world.json"]
const SUPPORTED_CAPABILITIES: Array[String] = [
	"realmz.core.classic-rules-v1",
	"realmz.presentation.content-addressed-media-v1",
	"realmz.presentation.battle-atlas-v1",
	"realmz.presentation.tileset-atlases-v1",
	"realmz.scenario.classic-vm-v1",
	"realmz.scenario.safe-actions-v1",
	"realmz.world.topology-v2",
]
const DEFERRED_PACKAGE_CAPABILITIES: Array[String] = [
	"realmz.scenario.gdscript-actions-v1",
]

var _last_error: String = ""
var _package_cache := PackageGraphCache.new()
var _receipt_store := PackageInstallReceiptStore.new(EXPECTED_SCHEMA_HASH, DECODER_VERSION)
var _archive_reader := PackageArchiveReader.new()
var _document_cache := PackageDocumentCacheScript.new(EXPECTED_SCHEMA_HASH, DECODER_VERSION)
var _manifest_discovery := PackageManifestDiscovery.new(EXPECTED_SCHEMA_HASH, SUPPORTED_CAPABILITIES, DEFERRED_PACKAGE_CAPABILITIES, _archive_reader)
var _media_validator := PackageMediaValidatorResolver.new()
var _domain_assembler := PackageDomainAssembler.new()


func promote_installed_package(path: String) -> void:
	var receipt := _receipt_store.read(path)
	if receipt.is_empty():
		return
	var cache_key := _receipt_store.cache_key(path, receipt)
	if _package_cache.get_result(cache_key) != null:
		_package_cache.promote(cache_key)
		return
	if _receipt_store.validate_archive_sha256(receipt, _archive_reader.sha256_file(path)):
		_package_cache.promote(cache_key)


func retained_package_count() -> int:
	return _package_cache.retained_count()


func close() -> void:
	_package_cache.clear()


func load_package(path: String, progress_callback: Callable = Callable(), cancel_callback: Callable = Callable()) -> PackageLoadResult:
	_last_error = ""
	if _cancel_requested(cancel_callback):
		return PackageLoadResult.failed(&"package_cancelled", "Package operation cancelled.")
	_report_progress(progress_callback, &"opening", 0, 1)
	var archive := ZIPReader.new()
	var open_error := archive.open(path)
	if open_error != OK:
		return PackageLoadResult.failed("package_open_failed", "Could not open package '%s' (error %d)." % [path, open_error])
	var result := _load_open_archive(archive, path, progress_callback, cancel_callback)
	archive.close()
	if result.is_ok():
		_report_progress(progress_callback, &"complete", 1, 1)
	return result


func load_bundled_package(path: String, expected_campaign_id: String, expected_package_hash: String) -> PackageLoadResult:
	_last_error = ""
	if expected_campaign_id.is_empty() or not _safe_path_component(expected_campaign_id) or not _is_sha256(expected_package_hash):
		return PackageLoadResult.failed(&"bundled_package_identity_invalid", "The bundled package identity is invalid.")
	var cache_key := "bundled:%s:%s:%s:%d" % [ProjectSettings.globalize_path(path).simplify_path(), expected_package_hash, EXPECTED_SCHEMA_HASH, DECODER_VERSION]
	var cached := _package_cache.get_result(cache_key)
	if cached != null:
		return cached
	var archive := ZIPReader.new()
	var open_error := archive.open(path)
	if open_error != OK:
		return PackageLoadResult.failed(&"package_open_failed", "Could not open bundled package '%s' (error %d)." % [path, open_error])
	# This immutable package is generated by Providence and its identity is pinned
	# in the application source. Release signing protects the shipped bytes, so
	# startup verifies the canonical manifest identity but does not rehash every
	# bundled portrait and combat icon on every launch.
	var trusted_identity := {
		"schemaHash": EXPECTED_SCHEMA_HASH,
		"campaignId": expected_campaign_id,
		"packageHash": expected_package_hash,
	}
	var result := _load_open_archive(archive, path, Callable(), Callable(), trusted_identity)
	archive.close()
	if result.is_ok():
		_package_cache.retain_candidate(cache_key, result)
	return result


func install_package(source_path: String, install_root: String = "user://packages", progress_callback: Callable = Callable(), cancel_callback: Callable = Callable()) -> PackageInstallResult:
	var installed_source := _load_installed_package(source_path, install_root, progress_callback, cancel_callback)
	if installed_source != null:
		if installed_source.is_ok():
			_report_progress(progress_callback, &"complete", 1, 1)
			return PackageInstallResult.succeeded(source_path, installed_source)
		return PackageInstallResult.failed(installed_source.error_code, installed_source.error_message)
	_report_progress(progress_callback, &"validating-source", 0, 1)
	var source := load_package(source_path, progress_callback, cancel_callback)
	if not source.is_ok():
		return PackageInstallResult.failed(source.error_code, source.error_message)
	if _cancel_requested(cancel_callback):
		return PackageInstallResult.failed(&"package_cancelled", "Package operation cancelled.")
	if not _safe_path_component(source.content.campaign_id):
		return PackageInstallResult.failed("campaign_path_unsafe", "Campaign ID cannot be used as a portable installation path.")
	var campaign_root := install_root.trim_suffix("/").path_join(source.content.campaign_id)
	var create_error := DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(campaign_root))
	if create_error != OK:
		return PackageInstallResult.failed("package_install_directory_failed", "Could not create the package installation directory (error %d)." % create_error)
	var target_path := campaign_root.path_join("%s.realmz2" % source.content.package_hash)
	if FileAccess.file_exists(target_path):
		if _same_package_path(source_path, target_path):
			if not _receipt_store.write(target_path, source.content, _archive_reader.sha256_file(target_path)):
				return PackageInstallResult.failed("package_receipt_write_failed", "Could not write the validated package installation receipt.")
			_report_progress(progress_callback, &"complete", 1, 1)
			return PackageInstallResult.succeeded(target_path, source)
		var existing := _load_installed_package(target_path, install_root, progress_callback, cancel_callback)
		if existing == null:
			existing = load_package(target_path, progress_callback, cancel_callback)
			if existing.is_ok() and not _receipt_store.write(target_path, existing.content, _archive_reader.sha256_file(target_path)):
				return PackageInstallResult.failed("package_receipt_write_failed", "Could not write the validated package installation receipt.")
		if existing.is_ok() and existing.content.package_hash == source.content.package_hash:
			_report_progress(progress_callback, &"complete", 1, 1)
			return PackageInstallResult.succeeded(target_path, existing)
		return PackageInstallResult.failed("package_install_collision", "An invalid package already occupies the immutable installation path.")
	_report_progress(progress_callback, &"copying-package", 0, 1)
	var temporary_path := target_path + ".installing"
	if FileAccess.file_exists(temporary_path):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(temporary_path))
	var source_bytes := FileAccess.get_file_as_bytes(source_path)
	if source_bytes.is_empty():
		return PackageInstallResult.failed("package_install_read_failed", "Could not read the source package for installation.")
	var temporary := FileAccess.open(temporary_path, FileAccess.WRITE)
	if temporary == null:
		return PackageInstallResult.failed("package_install_write_failed", "Could not open the temporary package installation file.")
	temporary.store_buffer(source_bytes)
	temporary.flush()
	temporary.close()
	if _cancel_requested(cancel_callback):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(temporary_path))
		return PackageInstallResult.failed(&"package_cancelled", "Package operation cancelled.")
	_report_progress(progress_callback, &"validating-install", 0, 1)
	var archive_sha256 := _archive_reader.sha256(source_bytes)
	var installed_bytes := FileAccess.get_file_as_bytes(temporary_path)
	if installed_bytes.size() != source_bytes.size() or _archive_reader.sha256(installed_bytes) != archive_sha256:
		DirAccess.remove_absolute(ProjectSettings.globalize_path(temporary_path))
		return PackageInstallResult.failed("package_install_readback_failed", "Temporary package installation failed byte-for-byte readback validation.")
	var rename_error := DirAccess.rename_absolute(ProjectSettings.globalize_path(temporary_path), ProjectSettings.globalize_path(target_path))
	if rename_error != OK:
		DirAccess.remove_absolute(ProjectSettings.globalize_path(temporary_path))
		return PackageInstallResult.failed("package_install_commit_failed", "Could not atomically install the verified package (error %d)." % rename_error)
	if not _receipt_store.write(target_path, source.content, archive_sha256):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(target_path))
		return PackageInstallResult.failed("package_receipt_write_failed", "Could not write the validated package installation receipt.")
	var installed := PackageLoadResult.succeeded(source.content, PackageMediaCatalog.new(target_path, source.content.package_hash, source.media.assets()))
	var receipt := _receipt_store.read(target_path)
	if not receipt.is_empty():
		_package_cache.retain_candidate(_receipt_store.cache_key(target_path, receipt), installed)
	_report_progress(progress_callback, &"complete", 1, 1)
	return PackageInstallResult.succeeded(target_path, installed)


func discover_packages(search_roots: Array[String]) -> Array[PackageDiscoveryResult]:
	return _manifest_discovery.discover_packages(search_roots)


func discover_campaigns(search_roots: Array[String]) -> Array[PackageDiscoveryResult]:
	return _manifest_discovery.discover_campaigns(search_roots)


func _same_package_path(left: String, right: String) -> bool:
	return ProjectSettings.globalize_path(left).simplify_path().to_lower() == ProjectSettings.globalize_path(right).simplify_path().to_lower()


func _load_installed_package(path: String, install_root: String, progress_callback: Callable = Callable(), cancel_callback: Callable = Callable()) -> PackageLoadResult:
	if not _is_installed_package_path(path, install_root):
		return null
	var receipt_path := PackageInstallReceiptStore.path_for(path)
	if not FileAccess.file_exists(receipt_path):
		return null
	_report_progress(progress_callback, &"checking-install", 0, 1)
	if _cancel_requested(cancel_callback):
		return PackageLoadResult.failed(&"package_cancelled", "Package operation cancelled.")
	var receipt := _receipt_store.read(path)
	if receipt.is_empty():
		return PackageLoadResult.failed(&"package_install_receipt_invalid", _receipt_store.last_error if not _receipt_store.last_error.is_empty() else "Installed package receipt is invalid.")
	var cache_key := _receipt_store.cache_key(path, receipt)
	var cached := _package_cache.get_result(cache_key)
	if cached != null:
		_report_progress(progress_callback, &"complete", 1, 1)
		return cached
	var archive_sha256: String = receipt["archiveSha256"]
	var cached_documents: Dictionary = _document_cache.read(path, archive_sha256)
	if cached_documents.is_empty():
		_report_progress(progress_callback, &"checking-install-integrity", 0, 1)
		archive_sha256 = _archive_reader.sha256_file(path)
		if not _receipt_store.validate_archive_sha256(receipt, archive_sha256):
			return PackageLoadResult.failed(&"package_install_receipt_invalid", _receipt_store.last_error)
		_report_progress(progress_callback, &"checking-install-integrity", 1, 1)
	else:
		_report_progress(progress_callback, &"restoring-runtime-image", 0, 1)
	if _cancel_requested(cancel_callback):
		return PackageLoadResult.failed(&"package_cancelled", "Package operation cancelled.")
	var archive := ZIPReader.new()
	var open_error := archive.open(path)
	if open_error != OK:
		return PackageLoadResult.failed(&"package_open_failed", "Could not open installed package '%s' (error %d)." % [path, open_error])
	var result := _load_open_archive(archive, path, progress_callback, cancel_callback, receipt, cached_documents)
	archive.close()
	if result.is_ok():
		_package_cache.retain_candidate(cache_key, result)
		_report_progress(progress_callback, &"complete", 1, 1)
	return result


func _is_installed_package_path(path: String, install_root: String) -> bool:
	var absolute_root := ProjectSettings.globalize_path(install_root).simplify_path().replace("\\", "/").trim_suffix("/").to_lower()
	var absolute_path := ProjectSettings.globalize_path(path).simplify_path().replace("\\", "/").to_lower()
	if not absolute_path.begins_with(absolute_root + "/"):
		return false
	var relative_path := absolute_path.trim_prefix(absolute_root + "/")
	var parts := relative_path.split("/", false)
	if parts.size() != 2 or not _safe_path_component(parts[0]) or not parts[1].ends_with(".realmz2"):
		return false
	return _is_sha256(parts[1].trim_suffix(".realmz2"))


func _receipt_matches_manifest(receipt: Dictionary, manifest: Dictionary) -> bool:
	if receipt["schemaHash"] != manifest["schemaHash"] or receipt["campaignId"] != manifest["campaignId"] or receipt["packageHash"] != manifest["packageHash"]:
		return _reject("Installed package manifest no longer matches its validated receipt.")
	return true


func _load_open_archive(archive: ZIPReader, source_path: String, progress_callback: Callable = Callable(), cancel_callback: Callable = Callable(), trusted_receipt: Dictionary = {}, cached_documents: Dictionary = {}) -> PackageLoadResult:
	var archive_entries_value: Variant = _archive_reader.entries(archive)
	var archive_entries: Array[String] = []
	if archive_entries_value != null:
		archive_entries = archive_entries_value
	if archive_entries_value == null:
		return _validation_failure()
	var manifest_value: Variant = _archive_reader.read_document(archive, "manifest.json")
	if manifest_value == null:
		return _validation_failure()
	var manifest: Dictionary = manifest_value
	if trusted_receipt.is_empty() and (not _manifest_discovery.validate_structure(manifest, archive_entries) or not _archive_reader.validate_files(manifest, archive, progress_callback, cancel_callback)):
		_last_error = _manifest_discovery.last_error if not _manifest_discovery.last_error.is_empty() else _archive_reader.last_error
		return _validation_failure()
	if not trusted_receipt.is_empty() and (not _manifest_discovery.validate_structure(manifest, archive_entries) or not _receipt_matches_manifest(trusted_receipt, manifest)):
		if not _manifest_discovery.last_error.is_empty():
			_last_error = _manifest_discovery.last_error
		return _validation_failure()
	var document_paths: Array[String] = ["content.json", "world.json", "scenario.json", "assets/index.json"]
	var documents_value: Variant = cached_documents
	if cached_documents.is_empty():
		_report_progress(progress_callback, &"reading-documents", 0, document_paths.size())
		documents_value = _archive_reader.read_documents(archive, document_paths, progress_callback)
	if documents_value == null:
		_last_error = _archive_reader.last_error
		return _validation_failure()
	var documents: Dictionary = documents_value
	var content_document: Dictionary = documents["content.json"]
	var world_document: Dictionary = documents["world.json"]
	var scenario_document: Dictionary = documents["scenario.json"]
	var asset_document: Dictionary = documents["assets/index.json"]
	if not _validate_document_header(content_document, "realmz2.content") or not _validate_document_header(world_document, "realmz2.world") or not _validate_document_header(scenario_document, "realmz2.scenario") or not _validate_document_header(asset_document, "realmz2.assets"):
		return _validation_failure()
	if trusted_receipt.is_empty():
		_media_validator.clear_error()
		if not _media_validator.validate_assets(asset_document, manifest["files"]):
			_last_error = _media_validator.error_message()
			return _validation_failure()
		if not _media_validator.validate_presentation_capabilities(manifest, asset_document):
			_last_error = _media_validator.error_message()
			return _validation_failure()
		if not _media_validator.validate_render_references(asset_document, world_document):
			_last_error = _media_validator.error_message()
			return _validation_failure()
	var runtime_assets := _media_validator.construct_assets(asset_document)
	_report_progress(progress_callback, &"constructing-content", 0, 1)
	var runtime_content := _domain_assembler.assemble(manifest, content_document, world_document, scenario_document, runtime_assets, not trusted_receipt.is_empty())
	if runtime_content == null:
		_last_error = _domain_assembler.error_message()
		return _validation_failure()
	if cached_documents.is_empty() and trusted_receipt.has("archiveSha256"):
		_document_cache.write(source_path, trusted_receipt["archiveSha256"], documents)
	return PackageLoadResult.succeeded(runtime_content, PackageMediaCatalog.new(source_path, manifest["packageHash"], runtime_assets))


static func package_capability_error(capability: Variant) -> String:
	if capability is String and DEFERRED_PACKAGE_CAPABILITIES.has(capability):
		return "Package requires sandboxed GDScript Scenario Actions, but no secure external host is available on this platform."
	if not capability is String or not SUPPORTED_CAPABILITIES.has(capability):
		return "Package requires unknown capability '%s'." % str(capability)
	return ""


func _validate_document_header(document: Dictionary, expected_kind: String) -> bool:
	if document.get("kind") != expected_kind or _integer(document.get("schemaVersion")) != 3:
		return _reject("Package document '%s' has an unsupported header." % expected_kind)
	return true


func _has_fields(value: Dictionary, fields: Array[String], label: String) -> bool:
	for field: String in fields:
		if not value.has(field):
			return _reject("%s is missing required field '%s'." % [label, field])
	return true


func _integer(value: Variant) -> int:
	if value is int:
		return value
	if value is float and is_equal_approx(value, round(value)):
		return int(value)
	return -1


func _is_integer(value: Variant) -> bool:
	return value is int or value is float and is_equal_approx(value, round(value))


func _is_sha256(value: Variant) -> bool:
	if not value is String or value.length() != 64:
		return false
	for character: String in value:
		if not character in "0123456789abcdef":
			return false
	return true


func _safe_path_component(value: String) -> bool:
	if value.is_empty() or value.length() > 128:
		return false
	for index: int in value.length():
		var code := value.unicode_at(index)
		var valid := (code >= 48 and code <= 57) or (code >= 65 and code <= 90) or (code >= 97 and code <= 122) or code == 45 or code == 95
		if not valid:
			return false
	return true


func _reject(message: String) -> bool:
	_last_error = message
	return false


func _validation_failure() -> PackageLoadResult:
	if _last_error == "Package operation cancelled.":
		return PackageLoadResult.failed(&"package_cancelled", _last_error)
	return PackageLoadResult.failed("package_validation_failed", _last_error if not _last_error.is_empty() else "Package validation failed.")


func _report_progress(callback: Callable, phase: StringName, completed: int, total: int) -> void:
	if callback.is_valid():
		callback.call(phase, completed, total)


func _cancel_requested(callback: Callable) -> bool:
	return callback.is_valid() and bool(callback.call())
